"""Batch 4: payment fields on Order and Donation

Revision ID: a6ce740e8e7e
Revises: b5c1d1474a6f
Create Date: 2026-09-30 11:33:41.561397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ce740e8e7e'
down_revision = 'b5c1d1474a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_video_testimonials_payment_ref'), ['payment_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_testimonials_payment_ref'))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_ref')

    # ### end Alembic commands ###
