"""Add payment_status and payment_ref to Order and Donation

Revision ID: ec9ba258e361
Revises: a6ce740e8e7e
Create Date: 2026-10-05 17:18:22.965782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9ba258e361'
down_revision = 'a6ce740e8e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_donations_payment_ref'), ['payment_ref'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_payment_ref'), ['payment_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_payment_ref'))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_ref')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_payment_ref'))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_ref')

    # ### end Alembic commands ###
